//#include "delegates\latex_delegate.h"
#include <cstdlib>
#include <string>
#include <cstdio>
#include <iostream>
using namespace std;
bool latex_exist_test()
{
    char latex_text[] = "\n\\documentclass{article}\n\\title{Test}\n\\author{tex2markdown}\n\\date{\\today}\n\\begin{document}\n\t\\maketitle\n\tHello BUILD!\n\\end{document}";
    system("mkdir latex_test");
    FILE *latex_text_file = freopen("latex_test/test_latex.tex","w+",stdout);
    cout << "% This is automatically generated by the program tex2markdown.\n% Never try to modify.";
    cout << latex_text << endl;
    fclose(latex_text_file);
    cout << "Output Test;";
    return true;
}
int main(){
    cout << "Test func latex_exist_test.\n";
    latex_exist_test();

    return 0;
}