#include "../include/delegates/latex_delegate.h"
#include <cstdlib>
#include <string>
#include <cstdio>
#include <iostream>
#include <fstream>
#include <cstring>
using namespace std;
latex_delegate::latex_delegate()
{

}
latex_delegate::~latex_delegate()
{

}
void latex_delegate::xelatex_compile(string filename)
{
    system(string("xelatex " + filename).data());
}

bool latex_delegate::latex_exist_test()
{
    char latex_text[] = "% This is automatically generated by the program tex2markdown.\n% Never try to modify.\n\\documentclass{article}\n\\title{Test}\n\\author{tex2markdown}\n\\date{\\today}\n\\begin{document}\n\t\\maketitle\n\tHello BUILD!\n\\end{document}";
    system("mkdir latex_test");
    FILE *latex_text_file = fopen("latex_test/test_latex.tex","w+");
    fwrite(latex_text,1,strlen(latex_text),latex_text_file);
    fclose(latex_text_file);
    xelatex_compile("latex_test/test_latex.tex");
    fstream __file;
    __file.open("latex_test/test_latex.tex",ios::in);
    if(!__file) return false;
    else return true;
}

int main()
{
    latex_delegate delegate;
    cout << "Test func latex_exist_test.\n";
    if(delegate.latex_exist_test()){
        cout << "(INFO)\tSuccessfully detected XeLaTeX engine.\n";
    } else {
        cout << "(ERROR)\tXeLaTeX not installed.\n(ERROR)\tConsult your computer administrator\n(ERROR)\tfor more information.";
    }

    return 0;
}